name: conpy312v2
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - python=3.12
  - matplotlib
  - numpy
  - reportlab
  - pydicom
  - pip
  - pyinstaller
  - pyside6
  - pytest
  - pythonocc-core=7.7.2
