"""Exercise nested diagram builds through the real command-line script."""

import hashlib
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

BUILD_SCRIPT = Path(__file__).resolve().parents[2] / "docs/architecture/build.py"


@pytest.fixture
def architecture(tmp_path: Path) -> Path:
    """Create an isolated build tree with two same-named diagrams in separate folders.

    This helper avoids rendering dependencies by supplying current SVGs. Broken discovery
    or path handling then fails the CLI assertions without mocking application modules.
    """
    shutil.copyfile(BUILD_SCRIPT, tmp_path / "build.py")
    (tmp_path / "viewer.html").write_text(
        "  <!-- BEGIN GENERATED by build.py. Do not edit. -->\n  <!-- END GENERATED -->\n"
    )
    (tmp_path / "README.md").write_text(
        "![Existing](diagrams/existing/uml.svg)\n![Proposed](diagrams/proposed/uml.svg)\n"
    )
    for folder in ("existing", "proposed"):
        diagram = tmp_path / "diagrams" / folder / "uml.mmd"
        diagram.parent.mkdir(parents=True)
        diagram.write_text(f"%% title: {folder}\n%% alt: {folder} diagram\nclassDiagram\n")
        stamp = hashlib.sha256(diagram.read_bytes()).hexdigest()
        diagram.with_suffix(".svg").write_text(
            f'<!-- source-sha256: {stamp} -->\n<svg viewBox="0 0 100 100"></svg>'
        )
    return tmp_path


def test_build_links_both_nested_diagrams(architecture: Path) -> None:
    """Build a viewer whose two image URLs resolve to different existing SVG files.

    Fails if discovery ignores subfolders or URL generation drops their names, which
    would leave the existing/projected architecture viewer empty or broken.
    """
    subprocess.run([sys.executable, str(architecture / "build.py")], check=True)
    viewer = (architecture / "viewer.html").read_text()
    assert 'src="diagrams/existing/uml.svg"' in viewer
    assert 'src="diagrams/proposed/uml.svg"' in viewer
    result = subprocess.run([sys.executable, str(architecture / "build.py"), "--check"])
    assert result.returncode == 0


@pytest.mark.parametrize("fault", ["missing", "stale", "unembedded"])
def test_check_rejects_invalid_nested_diagram(architecture: Path, fault: str) -> None:
    """Require the CLI to reject missing, stale or unembedded nested diagrams.

    Fails with exit zero if validation skips subfolders. Such a false success would
    let a PR ship diagrams that readers cannot see or that no longer match their source.
    """
    subprocess.run([sys.executable, str(architecture / "build.py")], check=True)
    diagram = architecture / "diagrams/proposed/uml.mmd"
    if fault == "missing":
        diagram.with_suffix(".svg").unlink()
    elif fault == "stale":
        diagram.write_text(diagram.read_text() + "class Added\n")
    else:
        (architecture / "README.md").write_text("![Existing](diagrams/existing/uml.svg)\n")
    result = subprocess.run(
        [sys.executable, str(architecture / "build.py"), "--check"],
        capture_output=True, text=True,
    )
    assert result.returncode == 1
    assert "STALE" in result.stdout
