"""Exercise docs/architecture/build.py: nested diagram builds and line-ending-safe stamps."""

import hashlib
import importlib.util
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

BUILD_SCRIPT = Path(__file__).resolve().parents[2] / "docs/architecture/build.py"

# sha256 of b"flowchart LR\n  a --> b\n", the LF form a Mac or Linux checkout holds.
LF_SOURCE_SHA256 = "6f6b792eff678dab26795dffd124a9c0b854ffb58de4355be3142a7cad880be2"


def load_build_module():
    """Import docs/architecture/build.py, which is a script and not an importable package.

    A helper, not a test. Loading it by path keeps the tests independent of sys.path.
    """
    spec = importlib.util.spec_from_file_location("architecture_build", BUILD_SCRIPT)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def write_diagram(folder: Path, source: bytes) -> Path:
    """Write flow.mmd with the given bytes, beside an SVG stamped with LF_SOURCE_SHA256.

    A helper, not a test. Returns the .mmd path, ready for svg_is_current().
    """
    mmd = folder / "flow.mmd"
    mmd.write_bytes(source)
    (folder / "flow.svg").write_text(f"<!-- source-sha256: {LF_SOURCE_SHA256} -->\n<svg></svg>\n")
    return mmd


@pytest.fixture
def architecture(tmp_path: Path) -> Path:
    """Create an isolated build tree with two same-named diagrams in separate folders.

    This helper avoids rendering dependencies by supplying current SVGs. Broken discovery
    or path handling then fails the CLI assertions without mocking application modules.
    The sources are written with LF endings on every OS, so the stamp computed here matches
    the LF hash build.py takes, and Windows does not see them as stale and try to render.
    """
    shutil.copyfile(BUILD_SCRIPT, tmp_path / "build.py")
    (tmp_path / "viewer.html").write_text(
        "  <!-- BEGIN GENERATED by build.py. Do not edit. -->\n  <!-- END GENERATED -->\n"
    )
    (tmp_path / "README.md").write_text(
        "![Existing](diagrams/existing/uml.svg)\n![Proposed](diagrams/proposed/uml.svg)\n"
    )
    for folder in ("existing", "proposed"):
        diagram = tmp_path / "diagrams" / folder / "uml.mmd"
        diagram.parent.mkdir(parents=True)
        diagram.write_text(f"%% title: {folder}\n%% alt: {folder} diagram\nclassDiagram\n", newline="\n")
        stamp = hashlib.sha256(diagram.read_bytes()).hexdigest()
        diagram.with_suffix(".svg").write_text(
            f'<!-- source-sha256: {stamp} -->\n<svg viewBox="0 0 100 100"></svg>'
        )
    return tmp_path


def test_build_links_both_nested_diagrams(architecture: Path) -> None:
    """Build a viewer whose two image URLs resolve to different existing SVG files.

    Fails if discovery ignores subfolders or URL generation drops their names, which
    would leave the existing/projected architecture viewer empty or broken.
    """
    subprocess.run([sys.executable, str(architecture / "build.py")], check=True)
    viewer = (architecture / "viewer.html").read_text()
    assert 'src="diagrams/existing/uml.svg"' in viewer
    assert 'src="diagrams/proposed/uml.svg"' in viewer
    result = subprocess.run([sys.executable, str(architecture / "build.py"), "--check"])
    assert result.returncode == 0


@pytest.mark.parametrize("fault", ["missing", "stale", "unembedded"])
def test_check_rejects_invalid_nested_diagram(architecture: Path, fault: str) -> None:
    """Require the CLI to reject missing, stale or unembedded nested diagrams.

    Fails with exit zero if validation skips subfolders. Such a false success would
    let a PR ship diagrams that readers cannot see or that no longer match their source.
    """
    subprocess.run([sys.executable, str(architecture / "build.py")], check=True)
    diagram = architecture / "diagrams/proposed/uml.mmd"
    if fault == "missing":
        diagram.with_suffix(".svg").unlink()
    elif fault == "stale":
        diagram.write_text(diagram.read_text() + "class Added\n")
    else:
        (architecture / "README.md").write_text("![Existing](diagrams/existing/uml.svg)\n")
    result = subprocess.run(
        [sys.executable, str(architecture / "build.py"), "--check"],
        capture_output=True, text=True,
    )
    assert result.returncode == 1
    assert "STALE" in result.stdout


def test_svg_is_current_when_source_is_checked_out_with_crlf(tmp_path: Path) -> None:
    """Check that an unchanged diagram checked out with CRLF line endings counts as current.

    Fails with False if build.py hashes the raw bytes. Git for Windows defaults to
    core.autocrlf=true and checks every .mmd out with CRLF, so the hash never matches a stamp
    written on macOS or Linux, and build.py --check blocks every pull request from Windows.
    """
    build = load_build_module()
    mmd = write_diagram(tmp_path, b"flowchart LR\r\n  a --> b\r\n")
    assert build.svg_is_current(mmd) is True


def test_svg_is_stale_when_source_text_changed(tmp_path: Path) -> None:
    """Check that a diagram whose text changed counts as stale.

    Fails with True if line-ending normalisation hides a real edit. A stale SVG would then
    pass build.py --check, and the picture a reviewer reads would not match its source.
    """
    build = load_build_module()
    mmd = write_diagram(tmp_path, b"flowchart LR\n  a --> c\n")
    assert build.svg_is_current(mmd) is False


@pytest.mark.skipif(shutil.which("npx") is None, reason="the diagram build needs Node")
def test_npx_names_a_program_this_machine_can_start() -> None:
    """Check that the npx command build.py renders with can actually be started here.

    Fails with FileNotFoundError if build.py starts npx by its bare name. On Windows npx is
    npx.cmd, which subprocess does not find by name, so every render crashes even with Node
    installed and no Windows clone can redraw a diagram. Skipped where Node is absent.
    """
    build = load_build_module()
    result = subprocess.run([build.npx(), "--version"], capture_output=True)
    assert result.returncode == 0
