#!/usr/bin/env python3
"""Build everything derived from the diagram sources in docs/architecture/diagrams/.

The only files a person edits are the `*.mmd` sources. This script derives the rest:

  * `diagrams/<name>.svg`  rendered from `<name>.mmd` with mermaid-cli (needs Node)
  * `viewer.html`          its list of pictures, discovered from the `*.mmd` files

`--check` also fails when `src/` has a module, package, model or view that
`system-architecture.mmd` does not name. That diagram is drawn by hand, so this is what keeps it
from going stale. The fix is to edit the `.mmd`, not to silence the check.

Usage, from anywhere:

  python docs/architecture/build.py              render whatever is stale, rewrite the viewer
  python docs/architecture/build.py --check      change nothing, exit 1 if anything is stale
  python docs/architecture/build.py --install-hook   build on a commit that touches a .mmd, check on one that touches src/

An SVG records the hash of its source in a leading comment, so "stale" means the hash does not
match, never a timestamp. The hash is taken over LF line endings, so a CRLF checkout matches.
Adding a diagram is: drop a `<name>.mmd` anywhere under diagrams/, run this, and embed its
relative SVG path in README.md. `--check` fails if a diagram is not embedded there.
"""
import argparse
import hashlib
import html
import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
DIAGRAMS = HERE / "diagrams"
VIEWER = HERE / "viewer.html"
README = HERE / "README.md"
MERMAID_CLI = "@mermaid-js/mermaid-cli@11"
STAMP = "<!-- source-sha256: {} -->"
STAMP_RE = re.compile(r"^<!-- source-sha256: ([0-9a-f]{64}) -->")
BEGIN = "  <!-- BEGIN GENERATED by build.py. Do not edit. -->"
END = "  <!-- END GENERATED -->"

SECTION = """  <section>
    <h2>{title}</h2>
    <div class="bar">
      <button type="button" data-act="out">Zoom out</button>
      <button type="button" data-act="in">Zoom in</button>
      <button type="button" data-act="reset">Reset</button>
      <span class="readout">100%</span>
    </div>
    <div class="stage" tabindex="0" aria-label="{title}. Scroll to zoom, drag to move.">
      <div class="sheet"><img src="diagrams/{name}.svg" width="{w}" height="{h}" alt="{alt}"></div>
    </div>
  </section>
"""


def sources():
    return sorted(DIAGRAMS.rglob("*.mmd"))


def digest(mmd):
    # Git on Windows checks text out with CRLF, so hash the LF form every clone agrees on.
    return hashlib.sha256(mmd.read_bytes().replace(b"\r\n", b"\n")).hexdigest()


def header(mmd, key):
    m = re.search(rf"^%% {key}: (.+)$", mmd.read_text(), re.M)
    if not m:
        sys.exit(f"{mmd.name} needs a first-lines comment '%% {key}: ...'")
    return m.group(1).strip()


def svg_is_current(mmd):
    svg = mmd.with_suffix(".svg")
    if not svg.exists():
        return False
    m = STAMP_RE.match(svg.read_text())
    return bool(m) and m.group(1) == digest(mmd)


def render(mmd):
    svg = mmd.with_suffix(".svg")
    subprocess.run(
        ["npx", "--yes", MERMAID_CLI, "-i", str(mmd), "-o", str(svg), "--quiet"],
        check=True,
    )
    svg.write_text(STAMP.format(digest(mmd)) + "\n" + svg.read_text())


def size(svg):
    m = re.search(r'viewBox="[-\d.]+ [-\d.]+ ([\d.]+) ([\d.]+)"', svg.read_text())
    if not m:
        sys.exit(f"{svg.name} has no viewBox")
    return round(float(m.group(1))), round(float(m.group(2)))


def viewer_body():
    parts = []
    for mmd in sources():
        w, h = size(mmd.with_suffix(".svg"))
        parts.append(SECTION.format(
            title=html.escape(header(mmd, "title")),
            alt=html.escape(header(mmd, "alt")),
            name=mmd.relative_to(DIAGRAMS).with_suffix("").as_posix(), w=w, h=h,
        ))
    return "\n".join(parts)


def viewer_text():
    text = VIEWER.read_text()
    a, b = text.index(BEGIN), text.index(END)
    return text[:a] + BEGIN + "\n" + viewer_body() + text[b:]


def unembedded():
    readme = README.read_text()
    return [
        m.relative_to(DIAGRAMS).with_suffix("").as_posix()
        for m in sources()
        if m.with_suffix(".svg").relative_to(HERE).as_posix() not in readme
    ]


SRC = HERE.parents[1] / "src"
SYSTEM_ARCHITECTURE = DIAGRAMS / "system-architecture.mmd"


def camel(stem):
    return "".join(w.capitalize() for w in stem.split("_"))


def named(stem, where):
    """True when `stem` appears as a whole word in `where`."""
    return re.search(rf"\b{re.escape(stem)}\b", where) is not None


def package_lines(text):
    """Map each `name: a, b, c` line of the diagram to its package name."""
    lines = {}
    for seg in re.split(r"<br/>|\"", text):
        m = re.match(r"\s*(\w+): (.*)", seg)
        if m:
            lines[m.group(1)] = m.group(2)
    return lines


def package_drift(src, lines):
    """Packages, and files inside them, that have no entry on their package's line."""
    classes = src / "classes"
    packages = sorted(p for p in classes.iterdir() if p.is_dir() and p.name != "__pycache__")
    missing = [
        f"package src/classes/{d.name}/ has no '{d.name}:' line"
        for d in packages
        if d.name not in lines
    ]
    for pkg in packages + [src / "settings"]:
        line = lines.get(pkg.name, "")
        for f in sorted(pkg.glob("*.py")):
            if f.stem != "__init__" and not named(f.stem, line):
                missing.append(f"{f.relative_to(src.parent)} is not on the '{pkg.name}:' line")
    return missing


def window_drift(src, text, folder, suffix, skip=()):
    """Models or views in src/windows/<folder> whose CamelCase name the diagram lacks."""
    missing = []
    for f in sorted((src / "windows" / folder).glob(f"*{suffix}.py")):
        name = camel(f.stem[: -len(suffix)]) if folder == "views" else camel(f.stem)
        if f.stem not in skip and not named(name, text):
            missing.append(f"{f.relative_to(src.parent)}: {name} is not named")
    return missing


def drift(src=SRC, mmd=SYSTEM_ARCHITECTURE):
    """Names in src/ that system-architecture.mmd does not mention.

    The system architecture is drawn by hand, so this is what stops it going stale: a new module,
    package, model or view fails `--check` until the diagram names it.
    """
    if not mmd.exists() or not src.exists():
        return []
    text = mmd.read_text()
    return (
        package_drift(src, package_lines(text))
        + window_drift(src, text, "models", "_model")
        + window_drift(src, text, "views", "_view", skip=("custom_view",))
    )


def check():
    problems = [f"{m.name}: its SVG is missing or its stamp does not match the source" for m in sources() if not svg_is_current(m)]
    if not problems and viewer_text() != VIEWER.read_text():
        problems.append("viewer.html does not list the current diagrams")
    problems += [f"{n}: not embedded in README.md" for n in unembedded()]
    problems += [f"system-architecture.mmd is out of date, {m}" for m in drift()]
    for p in problems:
        print("STALE", p)
    if problems:
        print("Run: python docs/architecture/build.py. If it reports system-architecture.mmd, edit that file first.")
    return 1 if problems else 0


def build():
    for mmd in sources():
        if not svg_is_current(mmd):
            print("render", mmd.name)
            render(mmd)
    VIEWER.write_text(viewer_text())
    for n in unembedded():
        print(f"WARNING {n} is not embedded in README.md. Add ![...](diagrams/{n}.svg).")
    return 0


HOOK = """#!/bin/sh
# Installed by docs/architecture/build.py --install-hook
if git diff --cached --name-only | grep -q '^docs/architecture/diagrams/.*\\.mmd$'; then
  python3 docs/architecture/build.py || exit 1
  git add docs/architecture/diagrams docs/architecture/viewer.html
fi
if git diff --cached --name-only | grep -q '^src/.*\\.py$'; then
  python3 docs/architecture/build.py --check || exit 1
fi
"""


def install_hook():
    root = subprocess.run(["git", "rev-parse", "--git-path", "hooks/pre-commit"],
                          cwd=HERE, capture_output=True, text=True, check=True).stdout.strip()
    hook = (HERE / root) if not Path(root).is_absolute() else Path(root)
    if hook.exists() and "build.py --install-hook" not in hook.read_text():
        sys.exit(f"{hook} already exists and is not ours. Add the build call to it by hand.")
    hook.write_text(HOOK)
    hook.chmod(0o755)
    print("installed", hook)
    return 0


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--install-hook", action="store_true")
    args = ap.parse_args()
    sys.exit(install_hook() if args.install_hook else check() if args.check else build())
